name: dagger

on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Check Go version
        run: go version

      - name: Check location
        run: ls -la

      - name: Run Dagger pipeline
        run: go run ci/main.go
